# Word bank for crossword generation - clue/answer pairs grouped by theme.
# All answers are <=9 letters (hard grid cap is 9x9 in logic.py).

WORD_BANK = {
    "animals": [
        {"clue": "Largest animal in the cat family", "answer": "LION"},
        {"clue": "Man's best friend", "answer": "DOG"},
        {"clue": "Slowest land mammal, lives in trees", "answer": "SLOTH"},
        {"clue": "Black and white bear from China", "answer": "PANDA"},
        {"clue": "Has a long neck, tallest animal", "answer": "GIRAFFE"},
        {"clue": "King of the jungle's home", "answer": "DEN"},
        {"clue": "Baby dog", "answer": "PUP"},
        {"clue": "Farm bird that says cluck", "answer": "HEN"},
        {"clue": "Buzzing insect that makes honey", "answer": "BEE"},
        {"clue": "Pond animal, says ribbit", "answer": "FROG"},
        {"clue": "Sea creature with eight arms", "answer": "OCTOPUS"},
        {"clue": "Nocturnal bird, hoots", "answer": "OWL"},
        {"clue": "Striped African horse", "answer": "ZEBRA"},
        {"clue": "Fast desert reptile", "answer": "LIZARD"},
        {"clue": "Common household pet, says meow", "answer": "CAT"},
        {"clue": "Small rodent, bigger cousin of a mouse", "answer": "RAT"},
        {"clue": "Flying mammal, active at night", "answer": "BAT"},
        {"clue": "Sly animal known for its bushy tail", "answer": "FOX"},
        {"clue": "Largest land animal, has a trunk", "answer": "ELEPHANT"},
        {"clue": "Playful primate that climbs trees", "answer": "MONKEY"},
        {"clue": "Long-eared animal known for hopping", "answer": "RABBIT"},
        {"clue": "Slow-moving reptile with a shell", "answer": "TURTLE"},
        {"clue": "Smart sea mammal known for clicking sounds", "answer": "DOLPHIN"},
        {"clue": "Flightless bird that lives in cold places", "answer": "PENGUIN"},
        {"clue": "Australian animal that hops and carries young in a pouch", "answer": "KANGAROO"},
        {"clue": "Fastest land animal", "answer": "CHEETAH"},
        {"clue": "Spotted big cat, strong climber", "answer": "LEOPARD"},
        {"clue": "Desert animal with humps", "answer": "CAMEL"},
        {"clue": "Stubborn farm animal, related to a horse", "answer": "DONKEY"},
        {"clue": "Small animal that gathers nuts", "answer": "SQUIRREL"},
        {"clue": "Small pet rodent that stores food in its cheeks", "answer": "HAMSTER"},
        {"clue": "Colorful talking bird", "answer": "PARROT"},
        {"clue": "Bird of prey known for its speed", "answer": "FALCON"},
        {"clue": "Eight-legged creature that spins webs", "answer": "SPIDER"},
        {"clue": "Hard-shelled flying insect", "answer": "BEETLE"},
        {"clue": "Chirping insect active at night", "answer": "CRICKET"},
        {"clue": "Small sea creature often eaten as seafood", "answer": "SHRIMP"},
        {"clue": "Sea creature with big claws", "answer": "LOBSTER"},
        {"clue": "Sea creature with a stinging, see-through body", "answer": "JELLYFISH"},
        {"clue": "Spiny sea creature shaped like a star", "answer": "STARFISH"},
        {"clue": "Small fish-like creature with a curled tail", "answer": "SEAHORSE"},
        {"clue": "Large reptile with sharp teeth, lives near rivers", "answer": "CROCODILE"},
        {"clue": "Wild animal that howls at night", "answer": "WOLF"},
        {"clue": "Big striped cat", "answer": "TIGER"},
        {"clue": "Large, furry forest animal that hibernates", "answer": "BEAR"},
        {"clue": "Forest animal known for its antlers", "answer": "DEER"},
        {"clue": "Farm animal known for headbutting", "answer": "GOAT"},
        {"clue": "Woolly farm animal", "answer": "SHEEP"},
        {"clue": "Animal you ride, says neigh", "answer": "HORSE"},
        {"clue": "Tiny rodent, afraid of cats", "answer": "MOUSE"},
    ],
    "plants": [
        {"clue": "Tall plant with a trunk and branches", "answer": "TREE"},
        {"clue": "Colorful part of a plant that smells nice", "answer": "FLOWER"},
        {"clue": "Underground part that absorbs water", "answer": "ROOT"},
        {"clue": "Colored substance in leaves used to capture light", "answer": "PIGMENT"},
        {"clue": "Where a plant starts growing from", "answer": "SEED"},
        {"clue": "Tallest type of grass", "answer": "BAMBOO"},
        {"clue": "Yellow flower that turns to face the sun", "answer": "SUNFLOWER"},
        {"clue": "Thin green part that grows from a stem", "answer": "LEAF"},
        {"clue": "Gas plants release that we breathe in", "answer": "OXYGEN"},
        {"clue": "Small juicy fruit with seeds on the outside", "answer": "BERRY"},
        {"clue": "Prickly desert plant", "answer": "CACTUS"},
        {"clue": "Plant grown for its edible root, orange in color", "answer": "CARROT"},
        {"clue": "Fungus that isn't quite a plant", "answer": "MUSHROOM"},
        {"clue": "Main upright part of a plant", "answer": "STEM"},
        {"clue": "Early flowering stage of a plant", "answer": "BLOSSOM"},
        {"clue": "Colorful leaf-like part of a flower", "answer": "PETAL"},
        {"clue": "Woody arm of a tree", "answer": "BRANCH"},
        {"clue": "Thick main stem of a tree", "answer": "TRUNK"},
        {"clue": "Large area thick with trees", "answer": "FOREST"},
        {"clue": "Dense tropical forest", "answer": "JUNGLE"},
        {"clue": "Open grassy field full of wildflowers", "answer": "MEADOW"},
        {"clue": "Place where fruit trees are grown", "answer": "ORCHARD"},
        {"clue": "The gathering of ripe crops", "answer": "HARVEST"},
        {"clue": "Describes soil rich enough for plants to thrive", "answer": "FERTILE"},
        {"clue": "The first tiny shoot of a growing plant", "answer": "SPROUT"},
        {"clue": "A young tree", "answer": "SAPLING"},
        {"clue": "Delicate flower often grown in greenhouses", "answer": "ORCHID"},
        {"clue": "Cup-shaped spring flower", "answer": "TULIP"},
        {"clue": "Small white and yellow flower", "answer": "DAISY"},
        {"clue": "Small plant with three leaves, sometimes lucky", "answer": "CLOVER"},
        {"clue": "Plant known for its stinging leaves", "answer": "NETTLE"},
        {"clue": "Soft green plant that grows on damp surfaces", "answer": "MOSS"},
        {"clue": "Living thing that includes mushrooms and mold", "answer": "FUNGUS"},
        {"clue": "Powder flowers use to reproduce", "answer": "POLLEN"},
        {"clue": "Sweet liquid flowers produce to attract insects", "answer": "NECTAR"},
        {"clue": "Sharp point on a rose stem", "answer": "THORN"},
        {"clue": "Climbing or trailing plant stem", "answer": "VINE"},
        {"clue": "Climbing plant that clings to walls", "answer": "IVY"},
        {"clue": "Strong tree known for acorns", "answer": "OAK"},
        {"clue": "Evergreen tree with needles and cones", "answer": "PINE"},
        {"clue": "Tree known for its sweet syrup", "answer": "MAPLE"},
        {"clue": "Tree with long drooping branches", "answer": "WILLOW"},
        {"clue": "Fragrant tree, its wood used for chests", "answer": "CEDAR"},
        {"clue": "Tree known for its papery white bark", "answer": "BIRCH"},
        {"clue": "Tall tropical tree with fronds", "answer": "PALM"},
    ],
    "science": [
        {"clue": "Smallest unit of matter", "answer": "ATOM"},
        {"clue": "Force that pulls objects toward Earth", "answer": "GRAVITY"},
        {"clue": "Study of living things", "answer": "BIOLOGY"},
        {"clue": "State of matter with no fixed shape or volume", "answer": "GAS"},
        {"clue": "Small sample examined closely under a microscope", "answer": "SPECIMEN"},
        {"clue": "Energy that lets us see", "answer": "LIGHT"},
        {"clue": "Basic unit of life", "answer": "CELL"},
        {"clue": "Change from liquid to gas", "answer": "EVAPORATE"},
        {"clue": "The study of matter and energy", "answer": "PHYSICS"},
        {"clue": "Frozen form of water", "answer": "ICE"},
        {"clue": "Instrument that measures air pressure", "answer": "BAROMETER"},
        {"clue": "Natural satellite of Earth", "answer": "MOON"},
        {"clue": "Lab equipment used to carry out a test", "answer": "APPARATUS"},
        {"clue": "Gas humans need to breathe", "answer": "OXYGEN"},
        {"clue": "Turning movement of the Earth causing day and night", "answer": "ROTATION"},
        {"clue": "Ability to do work, comes from food or fuel", "answer": "ENERGY"},
        {"clue": "Object that attracts iron", "answer": "MAGNET"},
        {"clue": "Force that slows down moving objects", "answer": "FRICTION"},
        {"clue": "Measure of how tightly packed matter is", "answer": "DENSITY"},
        {"clue": "Amount of space something takes up", "answer": "VOLUME"},
        {"clue": "Amount of matter in an object", "answer": "MASS"},
        {"clue": "A push or pull on an object", "answer": "FORCE"},
        {"clue": "The act of moving", "answer": "MOTION"},
        {"clue": "State of matter with a fixed shape", "answer": "SOLID"},
        {"clue": "State of matter that flows and takes the shape of its container", "answer": "LIQUID"},
        {"clue": "Space with no matter or air", "answer": "VACUUM"},
        {"clue": "Curved path an object takes around another", "answer": "ORBIT"},
        {"clue": "Large body that orbits a star", "answer": "PLANET"},
        {"clue": "Glowing ball of gas in the night sky", "answer": "STAR"},
        {"clue": "Icy space object with a glowing tail", "answer": "COMET"},
        {"clue": "When one object blocks light from another in space", "answer": "ECLIPSE"},
        {"clue": "Tool used to see faraway objects in space", "answer": "TELESCOPE"},
        {"clue": "A group of similar living organisms", "answer": "SPECIES"},
        {"clue": "The natural home of a plant or animal", "answer": "HABITAT"},
        {"clue": "A community of living things and their environment", "answer": "ECOSYSTEM"},
        {"clue": "Any living thing", "answer": "ORGANISM"},
        {"clue": "Tiny single-celled living things, some helpful, some harmful", "answer": "BACTERIA"},
        {"clue": "Tiny germ that can only reproduce inside living cells", "answer": "VIRUS"},
        {"clue": "Group of similar cells working together", "answer": "TISSUE"},
    ],
    "chemistry": [
        {"clue": "Chemical formula for water", "answer": "H2O"},
        {"clue": "Substance made of only one type of atom", "answer": "ELEMENT"},
        {"clue": "Table that organizes all known elements", "answer": "PERIODIC"},
        {"clue": "Smallest particle of an element", "answer": "ATOM"},
        {"clue": "Gas that makes up most of the air we breathe", "answer": "NITROGEN"},
        {"clue": "A substance formed when two elements combine", "answer": "COMPOUND"},
        {"clue": "Metal that is liquid at room temperature", "answer": "MERCURY"},
        {"clue": "Measure of how acidic or basic something is", "answer": "PH"},
        {"clue": "Lightest element in the universe", "answer": "HYDROGEN"},
        {"clue": "Chemical reaction combining a substance with oxygen", "answer": "OXIDATION"},
        {"clue": "Particle with a negative charge", "answer": "ELECTRON"},
        {"clue": "Shiny metal used in coins and jewelry", "answer": "GOLD"},
        {"clue": "Gas plants absorb, humans exhale", "answer": "CO2"},
        {"clue": "Common seasoning made of sodium and chlorine", "answer": "SALT"},
        {"clue": "Center of an atom", "answer": "NUCLEUS"},
        {"clue": "Substance that turns litmus paper red", "answer": "ACID"},
        {"clue": "Opposite of an acid, feels slippery", "answer": "BASE"},
        {"clue": "Shiny material that conducts electricity, like iron or copper", "answer": "METAL"},
        {"clue": "Element found in charcoal and diamonds", "answer": "CARBON"},
        {"clue": "Gas needed for burning and breathing", "answer": "OXYGEN"},
        {"clue": "Soft metal found in table salt", "answer": "SODIUM"},
        {"clue": "Yellow element with a rotten-egg smell", "answer": "SULFUR"},
        {"clue": "Element added to salt to protect the thyroid", "answer": "IODINE"},
        {"clue": "Light gas used to fill floating balloons", "answer": "HELIUM"},
        {"clue": "Gas used in glowing signs, glows orange-red", "answer": "NEON"},
        {"clue": "Gas used inside light bulbs to stop the filament burning", "answer": "ARGON"},
        {"clue": "Greenish gas used to disinfect swimming pools", "answer": "CHLORINE"},
        {"clue": "Element added to toothpaste to protect teeth", "answer": "FLUORINE"},
        {"clue": "A version of an element with a different number of neutrons", "answer": "ISOTOPE"},
        {"clue": "Substance that speeds up a chemical reaction", "answer": "CATALYST"},
        {"clue": "Mixture where one substance is fully dissolved in another", "answer": "SOLUTION"},
        {"clue": "Combination of substances that are not chemically joined", "answer": "MIXTURE"},
        {"clue": "A chemical change that produces new substances", "answer": "REACTION"},
        {"clue": "Smallest unit of a compound", "answer": "MOLECULE"},
        {"clue": "Positively charged particle in an atom's nucleus", "answer": "PROTON"},
        {"clue": "Particle in the nucleus with no charge", "answer": "NEUTRON"},
        {"clue": "Describes a substance that is a strong base", "answer": "ALKALI"},
        {"clue": "Element with properties of both metals and non-metals", "answer": "METALLOID"},
    ],
    "astrology": [
        {"clue": "Star at the center of our solar system", "answer": "SUN"},
        {"clue": "Red planet", "answer": "MARS"},
        {"clue": "Largest planet in the solar system", "answer": "JUPITER"},
        {"clue": "Ringed planet", "answer": "SATURN"},
        {"clue": "Planet we live on", "answer": "EARTH"},
        {"clue": "Symbol representing a zodiac group of stars", "answer": "STARSIGN"},
        {"clue": "Huge collection of stars, like the Milky Way", "answer": "GALAXY"},
        {"clue": "Object that orbits a planet", "answer": "MOON"},
        {"clue": "Closest planet to the Sun", "answer": "MERCURY"},
        {"clue": "Rock from space that hits Earth", "answer": "METEOR"},
        {"clue": "Path a planet takes around the Sun", "answer": "ORBIT"},
        {"clue": "Coldest, most distant known dwarf planet", "answer": "PLUTO"},
        {"clue": "Explosion of a dying star", "answer": "SUPERNOVA"},
        {"clue": "Person trained to travel in space", "answer": "ASTRONAUT"},
        {"clue": "Blue planet known for tilted rings", "answer": "URANUS"},
        {"clue": "Second planet from the Sun, hottest in the solar system", "answer": "VENUS"},
        {"clue": "Farthest known planet from the Sun", "answer": "NEPTUNE"},
        {"clue": "Icy space object with a glowing tail", "answer": "COMET"},
        {"clue": "When one space object blocks light from another", "answer": "ECLIPSE"},
        {"clue": "Chart based on the position of stars and planets", "answer": "ZODIAC"},
        {"clue": "Astrological reading based on your birth date", "answer": "HOROSCOPE"},
        {"clue": "Bowl-shaped dent left by a space impact", "answer": "CRATER"},
        {"clue": "Small rocky object orbiting the Sun", "answer": "ASTEROID"},
        {"clue": "Another word for the universe and everything in it", "answer": "COSMOS"},
        {"clue": "Cloud of dust and gas in space", "answer": "NEBULA"},
        {"clue": "Everything that exists, including all space and matter", "answer": "UNIVERSE"},
        {"clue": "Object placed in orbit to send signals back to Earth", "answer": "SATELLITE"},
        {"clue": "Vehicle used to travel into space", "answer": "ROCKET"},
        {"clue": "The act of sending a rocket into space", "answer": "LAUNCH"},
        {"clue": "Tool used to see faraway objects in space", "answer": "TELESCOPE"},
    ],
    "english": [
        {"clue": "A word that describes a noun", "answer": "ADJECTIVE"},
        {"clue": "A word that shows action", "answer": "VERB"},
        {"clue": "A person, place, or thing", "answer": "NOUN"},
        {"clue": "Word that replaces a noun, like 'he' or 'she'", "answer": "PRONOUN"},
        {"clue": "A story that is not true", "answer": "FICTION"},
        {"clue": "Opposite of a word", "answer": "ANTONYM"},
        {"clue": "Word that means the same as another", "answer": "SYNONYM"},
        {"clue": "The main, brave character in a story", "answer": "HERO"},
        {"clue": "A group of sentences about one idea", "answer": "PARAGRAPH"},
        {"clue": "Punctuation used to end a sentence", "answer": "PERIOD"},
        {"clue": "Word describing how an action is done, often ending in -ly", "answer": "ADVERB"},
        {"clue": "The beginning part of a story", "answer": "INTRO"},
        {"clue": "Repeating sounds at the end of lines in a poem", "answer": "RHYME"},
        {"clue": "A book that isn't real, made up", "answer": "NOVEL"},
        {"clue": "Punctuation mark that shows a short pause", "answer": "COMMA"},
        {"clue": "A group of words containing a subject and verb", "answer": "CLAUSE"},
        {"clue": "A small group of words that form a unit", "answer": "PHRASE"},
        {"clue": "A comparison using 'like' or 'as'", "answer": "SIMILE"},
        {"clue": "A comparison that says one thing IS another", "answer": "METAPHOR"},
        {"clue": "Spoken conversation between characters in a story", "answer": "DIALOGUE"},
        {"clue": "A person in a story", "answer": "CHARACTER"},
        {"clue": "Where and when a story takes place", "answer": "SETTING"},
        {"clue": "The problem or struggle in a story", "answer": "CONFLICT"},
        {"clue": "The central message or idea of a story", "answer": "THEME"},
        {"clue": "The category a piece of writing belongs to", "answer": "GENRE"},
        {"clue": "A group of lines in a poem", "answer": "STANZA"},
        {"clue": "A 14-line poem with a set structure", "answer": "SONNET"},
        {"clue": "The voice that tells a story", "answer": "NARRATOR"},
        {"clue": "The person who wrote a book", "answer": "AUTHOR"},
        {"clue": "A section of a book", "answer": "CHAPTER"},
        {"clue": "A complete thought made of words", "answer": "SENTENCE"},
        {"clue": "A letter like A, E, I, O, or U", "answer": "VOWEL"},
        {"clue": "A letter that isn't a vowel", "answer": "CONSONANT"},
        {"clue": "A single unit of sound in a word", "answer": "SYLLABLE"},
        {"clue": "The skill of writing words with correct letters", "answer": "SPELLING"},
    ],
    "social studies": [
        {"clue": "A large group of people with shared culture and land", "answer": "NATION"},
        {"clue": "Document that lists a country's basic laws", "answer": "CHARTER"},
        {"clue": "Person who leads a country", "answer": "PRESIDENT"},
        {"clue": "Line that separates two countries", "answer": "BORDER"},
        {"clue": "System where citizens vote for leaders", "answer": "DEMOCRACY"},
        {"clue": "Study of the Earth's land and people", "answer": "GEOGRAPHY"},
        {"clue": "A city that serves as the seat of government", "answer": "CAPITAL"},
        {"clue": "Group of people who share the same government", "answer": "CITIZENS"},
        {"clue": "Study of past events", "answer": "HISTORY"},
        {"clue": "Buying and selling of goods between countries", "answer": "TRADE"},
        {"clue": "Money system used by a country", "answer": "CURRENCY"},
        {"clue": "Right to choose leaders by voting", "answer": "SUFFRAGE"},
        {"clue": "Large landmass, like Africa or Asia", "answer": "CONTINENT"},
        {"clue": "Rules a society agrees to follow", "answer": "LAWS"},
        {"clue": "Part of government that makes laws", "answer": "SENATE"},
        {"clue": "A country's national law-making body", "answer": "CONGRESS"},
        {"clue": "The process of choosing leaders by vote", "answer": "ELECTION"},
        {"clue": "Formal agreement between two or more countries", "answer": "TREATY"},
        {"clue": "A partnership between countries or groups", "answer": "ALLIANCE"},
        {"clue": "A territory controlled by a distant country", "answer": "COLONY"},
        {"clue": "A large territory ruled by one power", "answer": "EMPIRE"},
        {"clue": "A king or queen who rules a country", "answer": "MONARCH"},
        {"clue": "A country governed by elected representatives", "answer": "REPUBLIC"},
        {"clue": "Money collected by the government from citizens", "answer": "TAXATION"},
        {"clue": "The system of money, jobs, and trade in a country", "answer": "ECONOMY"},
        {"clue": "The making of goods in factories", "answer": "INDUSTRY"},
        {"clue": "The customs, beliefs, and arts of a group of people", "answer": "CULTURE"},
        {"clue": "A custom passed down through generations", "answer": "TRADITION"},
        {"clue": "A famous place or structure worth visiting", "answer": "LANDMARK"},
        {"clue": "A structure built to honor a person or event", "answer": "MONUMENT"},
        {"clue": "An official count of a country's population", "answer": "CENSUS"},
        {"clue": "The buying and selling of goods and services", "answer": "COMMERCE"},
        {"clue": "A person who moves to a new country to live", "answer": "IMMIGRANT"},
    ],
}
