"""add xp tracking and 24h streak expiry

Revision ID: 044e4da4b2c0
Revises: 2bceb0cbe239
Create Date: 2026-08-23 03:47:59.608936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044e4da4b2c0'
down_revision: Union[str, Sequence[str], None] = '2bceb0cbe239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid_leaderboard_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_leaderboard_scores_id'), 'kid_leaderboard_scores', ['id'], unique=False)
    op.create_index(op.f('ix_kid_leaderboard_scores_kid_id'), 'kid_leaderboard_scores', ['kid_id'], unique=True)
    op.create_table('kid_level_start_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid_id', 'level_id', name='uq_kid_level_start_claim')
    )
    op.create_index(op.f('ix_kid_level_start_claims_id'), 'kid_level_start_claims', ['id'], unique=False)
    op.create_index(op.f('ix_kid_level_start_claims_kid_id'), 'kid_level_start_claims', ['kid_id'], unique=False)
    op.create_index(op.f('ix_kid_level_start_claims_level_id'), 'kid_level_start_claims', ['level_id'], unique=False)
    op.create_table('kid_slot_solve_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid_id', 'level_id', 'slot_number', name='uq_kid_slot_solve_claim')
    )
    op.create_index(op.f('ix_kid_slot_solve_claims_id'), 'kid_slot_solve_claims', ['id'], unique=False)
    op.create_index(op.f('ix_kid_slot_solve_claims_kid_id'), 'kid_slot_solve_claims', ['kid_id'], unique=False)
    op.create_index(op.f('ix_kid_slot_solve_claims_level_id'), 'kid_slot_solve_claims', ['level_id'], unique=False)
    op.add_column('kid_game_progress', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('kid_game_progress', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('kid_game_progress', sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kid_game_progress', 'last_completed_at')
    op.drop_column('kid_game_progress', 'longest_streak')
    op.drop_column('kid_game_progress', 'current_streak')
    op.drop_index(op.f('ix_kid_slot_solve_claims_level_id'), table_name='kid_slot_solve_claims')
    op.drop_index(op.f('ix_kid_slot_solve_claims_kid_id'), table_name='kid_slot_solve_claims')
    op.drop_index(op.f('ix_kid_slot_solve_claims_id'), table_name='kid_slot_solve_claims')
    op.drop_table('kid_slot_solve_claims')
    op.drop_index(op.f('ix_kid_level_start_claims_level_id'), table_name='kid_level_start_claims')
    op.drop_index(op.f('ix_kid_level_start_claims_kid_id'), table_name='kid_level_start_claims')
    op.drop_index(op.f('ix_kid_level_start_claims_id'), table_name='kid_level_start_claims')
    op.drop_table('kid_level_start_claims')
    op.drop_index(op.f('ix_kid_leaderboard_scores_kid_id'), table_name='kid_leaderboard_scores')
    op.drop_index(op.f('ix_kid_leaderboard_scores_id'), table_name='kid_leaderboard_scores')
    op.drop_table('kid_leaderboard_scores')
    # ### end Alembic commands ###
