"""add gamemanager tables

Revision ID: 2bceb0cbe239
Revises: a8a20ec8d647
Create Date: 2026-08-23 01:29:42.782606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bceb0cbe239'
down_revision: Union[str, Sequence[str], None] = 'a8a20ec8d647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('grid_rows', sa.Integer(), nullable=False),
    sa.Column('grid_cols', sa.Integer(), nullable=False),
    sa.Column('blocked_cells', sa.JSON(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('solution', sa.JSON(), nullable=False),
    sa.Column('completion_reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_levels_game_type'), 'game_levels', ['game_type'], unique=False)
    op.create_index(op.f('ix_game_levels_id'), 'game_levels', ['id'], unique=False)
    op.create_table('kid_game_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('completed_levels', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid_id', 'game_type', name='uq_kid_game_progress')
    )
    op.create_index(op.f('ix_kid_game_progress_game_type'), 'kid_game_progress', ['game_type'], unique=False)
    op.create_index(op.f('ix_kid_game_progress_id'), 'kid_game_progress', ['id'], unique=False)
    op.create_index(op.f('ix_kid_game_progress_kid_id'), 'kid_game_progress', ['kid_id'], unique=False)
    op.create_table('kid_level_bonus_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid_id', 'level_id', 'slot_number', name='uq_kid_level_slot_claim')
    )
    op.create_index(op.f('ix_kid_level_bonus_claims_id'), 'kid_level_bonus_claims', ['id'], unique=False)
    op.create_index(op.f('ix_kid_level_bonus_claims_kid_id'), 'kid_level_bonus_claims', ['kid_id'], unique=False)
    op.create_index(op.f('ix_kid_level_bonus_claims_level_id'), 'kid_level_bonus_claims', ['level_id'], unique=False)
    op.create_table('kid_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('keys', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_wallets_id'), 'kid_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_kid_wallets_kid_id'), 'kid_wallets', ['kid_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kid_wallets_kid_id'), table_name='kid_wallets')
    op.drop_index(op.f('ix_kid_wallets_id'), table_name='kid_wallets')
    op.drop_table('kid_wallets')
    op.drop_index(op.f('ix_kid_level_bonus_claims_level_id'), table_name='kid_level_bonus_claims')
    op.drop_index(op.f('ix_kid_level_bonus_claims_kid_id'), table_name='kid_level_bonus_claims')
    op.drop_index(op.f('ix_kid_level_bonus_claims_id'), table_name='kid_level_bonus_claims')
    op.drop_table('kid_level_bonus_claims')
    op.drop_index(op.f('ix_kid_game_progress_kid_id'), table_name='kid_game_progress')
    op.drop_index(op.f('ix_kid_game_progress_id'), table_name='kid_game_progress')
    op.drop_index(op.f('ix_kid_game_progress_game_type'), table_name='kid_game_progress')
    op.drop_table('kid_game_progress')
    op.drop_index(op.f('ix_game_levels_id'), table_name='game_levels')
    op.drop_index(op.f('ix_game_levels_game_type'), table_name='game_levels')
    op.drop_table('game_levels')
    # ### end Alembic commands ###
