"""add is_favorite to subjects

Revision ID: 6dac39cf5f6d
Revises: 0e59512fd1f4
Create Date: 2026-08-28 11:20:15.181189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dac39cf5f6d'
down_revision: Union[str, Sequence[str], None] = '0e59512fd1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'is_favorite')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###
