"""baseline

Revision ID: a8a20ec8d647
Revises: 
Create Date: 2026-08-19 09:50:10.635497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a20ec8d647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('family_name_for_kids', sa.String(), nullable=True),
    sa.Column('parent_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name='phone_must_have_country_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=True)
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sessions_owner_type'), 'sessions', ['owner_type'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('email_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_id'), 'email_verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_parent_id'), 'email_verification_codes', ['parent_id'], unique=False)
    op.create_table('kids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('learning_system', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kids_id'), 'kids', ['id'], unique=False)
    op.create_index(op.f('ix_kids_parent_id'), 'kids', ['parent_id'], unique=False)
    op.create_table('parent_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_passwords_id'), 'parent_passwords', ['id'], unique=False)
    op.create_index(op.f('ix_parent_passwords_parent_id'), 'parent_passwords', ['parent_id'], unique=True)
    op.create_table('parent_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_reset_codes_id'), 'parent_reset_codes', ['id'], unique=False)
    op.create_index(op.f('ix_parent_reset_codes_parent_id'), 'parent_reset_codes', ['parent_id'], unique=False)
    op.create_table('kid_claim_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_claim_tokens_id'), 'kid_claim_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_kid_claim_tokens_kid_id'), 'kid_claim_tokens', ['kid_id'], unique=False)
    op.create_table('kid_info',
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('favorite_color', sa.String(), nullable=True),
    sa.Column('favorite_animal', sa.String(), nullable=True),
    sa.Column('subjects_loved', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('kid_id')
    )
    op.create_index(op.f('ix_kid_info_kid_id'), 'kid_info', ['kid_id'], unique=False)
    op.create_table('kid_login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_login_tokens_id'), 'kid_login_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_kid_login_tokens_kid_id'), 'kid_login_tokens', ['kid_id'], unique=False)
    op.create_table('kid_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_passwords_id'), 'kid_passwords', ['id'], unique=False)
    op.create_index(op.f('ix_kid_passwords_kid_id'), 'kid_passwords', ['kid_id'], unique=True)
    op.create_table('kid_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_reset_codes_id'), 'kid_reset_codes', ['id'], unique=False)
    op.create_index(op.f('ix_kid_reset_codes_kid_id'), 'kid_reset_codes', ['kid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kid_reset_codes_kid_id'), table_name='kid_reset_codes')
    op.drop_index(op.f('ix_kid_reset_codes_id'), table_name='kid_reset_codes')
    op.drop_table('kid_reset_codes')
    op.drop_index(op.f('ix_kid_passwords_kid_id'), table_name='kid_passwords')
    op.drop_index(op.f('ix_kid_passwords_id'), table_name='kid_passwords')
    op.drop_table('kid_passwords')
    op.drop_index(op.f('ix_kid_login_tokens_kid_id'), table_name='kid_login_tokens')
    op.drop_index(op.f('ix_kid_login_tokens_id'), table_name='kid_login_tokens')
    op.drop_table('kid_login_tokens')
    op.drop_index(op.f('ix_kid_info_kid_id'), table_name='kid_info')
    op.drop_table('kid_info')
    op.drop_index(op.f('ix_kid_claim_tokens_kid_id'), table_name='kid_claim_tokens')
    op.drop_index(op.f('ix_kid_claim_tokens_id'), table_name='kid_claim_tokens')
    op.drop_table('kid_claim_tokens')
    op.drop_index(op.f('ix_parent_reset_codes_parent_id'), table_name='parent_reset_codes')
    op.drop_index(op.f('ix_parent_reset_codes_id'), table_name='parent_reset_codes')
    op.drop_table('parent_reset_codes')
    op.drop_index(op.f('ix_parent_passwords_parent_id'), table_name='parent_passwords')
    op.drop_index(op.f('ix_parent_passwords_id'), table_name='parent_passwords')
    op.drop_table('parent_passwords')
    op.drop_index(op.f('ix_kids_parent_id'), table_name='kids')
    op.drop_index(op.f('ix_kids_id'), table_name='kids')
    op.drop_table('kids')
    op.drop_index(op.f('ix_email_verification_codes_parent_id'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_id'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_type'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
