"""regen kid_info and kid_claim_tokens

Revision ID: temp_regen
Revises: a1b2c3d4e5f6
Create Date: 2026-08-09 23:49:34.857237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'temp_regen'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('info_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=True)
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_table('kids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('learning_system', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kids_id'), 'kids', ['id'], unique=False)
    op.create_table('kid_claim_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_claim_tokens_id'), 'kid_claim_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_kid_claim_tokens_token'), 'kid_claim_tokens', ['token'], unique=True)
    op.create_table('kid_info',
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('subjects_loved', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('favorite_color', sa.String(), nullable=True),
    sa.Column('favorite_animal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('kid_id')
    )
    op.create_index(op.f('ix_kid_info_kid_id'), 'kid_info', ['kid_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ),
    sa.PrimaryKeyConstraint('kid_id')
    )
    op.create_index(op.f('ix_user_progress_kid_id'), 'user_progress', ['kid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_kid_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_kid_info_kid_id'), table_name='kid_info')
    op.drop_table('kid_info')
    op.drop_index(op.f('ix_kid_claim_tokens_token'), table_name='kid_claim_tokens')
    op.drop_index(op.f('ix_kid_claim_tokens_id'), table_name='kid_claim_tokens')
    op.drop_table('kid_claim_tokens')
    op.drop_index(op.f('ix_kids_id'), table_name='kids')
    op.drop_table('kids')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
